### ISSUE TITLE
Include fields from Graylog log messages in alert to Jira  Problem

### ISSUE THREAD

**Issue by ps-gm** [magicdude4eva/graylog-jira-alarmcallback#13]
The plugin is working perfectly fine and we get alerts to Jira, which is super fine! Thanks for this awesome integration. 
One thing as we are using 2.0.3 Graylog is that we have disabled the "map-plugin" as mentioned. Now we don't get any [LAST_MESSAGE.XXXX] information into Jira. The other fields are working fine. Is there anything known that this is not working. We are having Syslog messages in Graylog which should then be alerted into Jira. Many many thanks in advance!!!

**Comment by magicdude4eva** [comment]
Hi there, this is a known issue with Graylog where in certain cases the LAST_MESSAGE is not passed on. 

Two issues logged:
- https://github.com/Graylog2/graylog2-server/issues/2382
- https://github.com/Graylog2/graylog2-server/issues/2387

It does not look like this is going to be fixed before 2.1.

**Comment by ps-gm** [comment]
Sorry for bringing in a comment and ticket too fast! The plugin is working perfectly fine on Graylog 2.0.3 and there are no problems in using it. Also the extracted message tuples are being transferred to Jira correctly - It was a configuration problem on our side with "0" messages being set to be sent under the "Stream"->"Alert" -> "Conditions". Thanks for your endeavors, which are really appreciated!!!

**Comment by magicdude4eva** [comment]
No problem. Great to see that it works for you 👍
