### ISSUE TITLE
Ticket will not be created if Field Message Regex is usewd

### ISSUE THREAD

**Issue by janwagners** [magicdude4eva/graylog-jira-alarmcallback#14]
Hi Gerd,

again i'm running into issues that i don't understand.

At first my current setup:
- Graylog 2.0.3-1
- Graylog-jira-alarmcallback 1.0.8
- Jira 6.4.3

When i trigger a stream using a message regex in the alarmcallback the graylog-server is complaining several times about the field graylog_md5. You can see this in the following extract of the graylog sever.log:

[graylog-error.txt](https://github.com/magicdude4eva/graylog-jira-alarmcallback/files/538529/graylog-error.txt)

When i don't use the message regex field the issue is created sucessfully. So here is the config of the alarm callback:

[alarmcallback-config.txt](https://github.com/magicdude4eva/graylog-jira-alarmcallback/files/538543/alarmcallback-config.txt)

Can you explain this behaviour? I don't need to use the md5 field.

Another question is about my used regex. Is it possible to use Reg Ex Groups in your plugins. I need to  use the first group of the reg ex result.

Please let me know if anything in unclear.

Thanks and regards,

Jan

**Comment by magicdude4eva** [comment]
Is there any chance to possibly upgrade to Graylog 2.1? Between Graylog 2.0.1 and 2.1 there have been a few issues regarding how messages are passed into plugins.

There was also an issue with Graylog where an empty plugin-parameter field was still passed as a value to plugin and I think that your MD5 issue originates from that issue in Graylog as my plugin-code would only search for an issue if the message digest is provided:

![image](https://cloud.githubusercontent.com/assets/1632781/19515507/22b2884a-95f8-11e6-8961-4ecb4a15a630.png)

I unfortunately do not support regex-groups and one option would perhaps be to use an extractor in Graylog to extract what you need into a message?

**Comment by janwagners** [comment]
Hi Gerd,

sorry for my late response. At the moment i'm involved in other critical issues.

We have planned to upgrade Graylog in the near future :-). So i hope this will solve our problem.

I've managed it to extract the specific content of the message into a field. Can i use this field with your plugin in the jira alarm callback like in the normal email callback?

Thanks and regards,

Jan

**Comment by janwagners** [comment]
Hi Gerd,

i recently updated our graylog server and now everything is working fine. Even the extracted variables (graylog extractor for the message) are included successfully into the ticket.

Thank you very much and regards,

Jan

**Comment by magicdude4eva** [comment]
Thanks for the update @janwagners - glad that this worked.
