### ISSUE TITLE
Field Names need to be specified all in CAPS

### ISSUE THREAD

**Issue by 123dev** [magicdude4eva/graylog-jira-alarmcallback#3]
Hi Gerd,
_Splitting from: [issue](https://github.com/magicdude4eva/graylog-jira-alarmcallback/issues/1)_

It looks like Field names have to be all caps. (no problem, updated my template)
So what happens when we have two fields that differ only in casing?
level and Level for example?

> 1. Case of message fields
> There is no reason why this can not be case sensitive. I never thought that a message could have multiple fields with the same name but different case. I can change it and be case-sensitive if you need it (then just log an issue)

**Comment by magicdude4eva** [comment]
This is fixed in the next release.

**Comment by 123dev** [comment]
Thanks Gerd.

I can confirm that this is working in 1.0.4 release.
Many thanks
