### ISSUE TITLE
When a field has no value, it would be nice if it is replaced with blanks rather than show up as [LAST_MESSAGE.FIELD]

### ISSUE THREAD

**Issue by 123dev** [magicdude4eva/graylog-jira-alarmcallback#4]
_Splitting from [issue](https://github.com/magicdude4eva/graylog-jira-alarmcallback/issues/1)_

Not a bug, but nice to have.
When a field has no value, it would be nice if it is replaced with blanks rather than show up as [LAST_MESSAGE.FIELD]

**Comment by magicdude4eva** [comment]
This is fixed in the next release.

**Comment by 123dev** [comment]
Thanks Gerd.

I can confirm that this is working in 1.0.4 release.
Many thanks
