### ISSUE TITLE
Make duplicate Jira Issue states configureable

### ISSUE THREAD

**Issue by swimmesberger** [magicdude4eva/graylog-jira-alarmcallback#5]
Would be nice to manully configure the states of the Jira issue which affect the plugin status if the issue is a duplicate or not (https://github.com/magicdude4eva/graylog-jira-alarmcallback/blob/master/src/main/java/com/bidorbuy/graylog/jira/callback/JiraAlarmCallback.java#L137). 
When you use custom states in your Jira instance the filter which is applied in the referenced line does not match under some circumstances.
It would be generally nice to manully customize the query so you are able to do custom filtering additionally to the hash check. 
(Maybe even so far customizeable that you are able to completely remove the additional check and simply use the md5)

**Comment by magicdude4eva** [comment]
Hi there, 

thanks for the suggestion. I have made the filter-query optional and added your enhancement in release [1.0.4](https://github.com/magicdude4eva/graylog-jira-alarmcallback/releases/tag/1.0.4).

If you do not specify a filter-query, then the Jira project is searched for any issue matching the MD5 and will then not log an issue. This will be problematic if an issue with the MD5 has previously been fixed and resurfaced, in which case you will not know.

**Comment by 123dev** [comment]
Thanks Gerd.

swimmesberger, this is a nice feature
I can confirm that this is working in 1.0.4 release.

Thanks

**Comment by swimmesberger** [comment]
Very nice - thanks for the fast response! Couple of things to consider:

>  This will be problematic if an issue with the MD5 has previously been fixed and resurfaced, in which case you will not know.

Yeah sure makes totally sense but maybe for some the MD5 is "unique" enough because they use some combination of custom fields.

> If you do not specify a filter-query, then the Jira project is searched for any issue matching the MD5

Wouldn't it be better to **explicitly** (by maybe setting the config explicitly empty or something like that) set this behaviour and default to the old behaviour so the new version doesn't break existing installations when making a minor update. For default jira installations the "AND Status not in (Closed, Done, Resolved)" seems also very reasonable it just starts to get tricky when a custom workflow is used.

**Comment by magicdude4eva** [comment]
Agree with the MD5 being unique if it consists of unique field content.

The Graylog plugin config feature is really bad and somewhat broken in the API - as an example: when providing a default value and then erasing it to blank, Graylog still stores the default value (this was also reported as issue #2).

I was forced to have default values in the help-description and will have a look if there is not a workaround (or if I perhaps do something wrong - nothing obvious though).

**Comment by magicdude4eva** [comment]
Closing this issue as this is now configurable. I have logged an issue with Graylog to get the default-values fixed and will then revisit the showing of default-values. I think this might however only be fixed in Graylog 2.
