### ISSUE TITLE
JIRA task title field is not being picked up.

### ISSUE THREAD

**Issue by 123dev** [magicdude4eva/graylog-jira-alarmcallback#6]
JIRA task title field is not being picked up in version 1.0.4
_This was working in version 1.0.3_

I have ```ErrorCode:5000000 on [LAST_MESSAGE._uri_stem_base] ``` in the **JIRA task title** Settings
But I'm getting ```[Alert] Graylog alert for stream: ErrorCode:5000000``` in Jira Title.

I even tested it with ```ErrorCode:5000000 on [LAST_MESSAGE._URI_STEM_BASE] ```
and no go, which by the way was the **JIRA task title** settings I was using with 1.0.3 (before [this fix](https://github.com/magicdude4eva/graylog-jira-alarmcallback/issues/3)

**[LAST_MESSAGE._uri_stem_base]** is working fine in the **Message template** and  **JIRA MD5 pattern**

**Comment by magicdude4eva** [comment]
Fixed in [1.0.5](https://github.com/magicdude4eva/graylog-jira-alarmcallback/releases/tag/1.0.5)

**Comment by 123dev** [comment]
Thanks Gerd.

I can confirm that this is working in 1.0.5

**Comment by magicdude4eva** [comment]
Thanks for testing and feedback.
