### ISSUE TITLE
Stream Alert rule is showing up in the Jira description

### ISSUE THREAD

**Issue by 123dev** [magicdude4eva/graylog-jira-alarmcallback#7]
Hi Gerd,

Splitting from the [issue](https://github.com/magicdude4eva/graylog-jira-alarmcallback/issues/1)

```Stream had 1 messages in the last 1 minutes with trigger condition more than 0 messages. (Current grace time: 0 minutes)``` is showing up as the first line in the Jira description even though I have not set up [ALERT_TRIGGERED_CONDITION]

Thanks

**Comment by magicdude4eva** [comment]
This would only be displayed if you have a `[ALERT_TRIGGERED_CONDITION]` configured in the template.

Can you just paste the content of the `jira_message_template` and the full text of a JIRA issue description?

**Comment by 123dev** [comment]
Hi Gerd,

Yeah, I don't have ```[ALERT_TRIGGERED_CONDITION]``` configured in the template.

Here's the head of the template (I have many more graylog fields listed, but nothing about the [ALERT_TRIGGERED_CONDITION])
```*Stream title:* [STREAM_TITLE]\n*Stream URL:* [STREAM_URL]\n*Alert triggered at:* [ALERT_TRIGGERED_AT]\n*Source:* [LAST_MESSAGE.source]\n\n*ErrorCode:* [LAST_MESSAGE.ErrorCode]\n*date:* [LAST_MESSAGE.date]\n*time:* [LAST_MESSAGE.time]\n\n*correlation_id:* [[LAST_MESSAGE.correlation_id]|http://123hub?cid=[LAST_MESSAGE.correlation_id]]\n*uri_stem_base:* {noformat}[LAST_MESSAGE._uri_stem_base]{noformat}\n*uri_stem:* [LAST_MESSAGE.uri_stem]\n*method:* [LAST_MESSAGE.method]\n{code:title=request_headers}[LAST_MESSAGE.request_headers]{code}\n{code:title=request_payload}[LAST_MESSAGE.request_payload]{code}\n*request_payload_length:* [LAST_MESSAGE.request_payload_length]\n{code:title=response_headers}[LAST_MESSAGE.response_headers]{code}\n{code:title=response_payload}[LAST_MESSAGE.response_payload]{code}\n```

And here's what shows up in Jira
![jira_description](https://cloud.githubusercontent.com/assets/13109154/14688946/0aea34b6-0713-11e6-80f8-93c9db1e3658.png)

Thanks for looking into this, and let me know if you need any additional information.

**Comment by magicdude4eva** [comment]
Thanks for the details. I found the issue (it was so obvious and in front of me that I overlooked it all the time - hahaha). 

Fixed in release [1.0.6](https://github.com/magicdude4eva/graylog-jira-alarmcallback/releases/tag/1.0.6)

**Comment by 123dev** [comment]
Thanks Gerd,

So you're human? ;)
I can confirm that this is working fine in 1.0.6

**Comment by magicdude4eva** [comment]
Most of the time :-)
